### ISSUE TITLE
datecmp 코드 작성

### ISSUE THREAD

**Issue by kchs0529** [DohyoungSeong/Project2#11]
//두 개의 파일 크기를 비교하는 함수 작성
void sizecmp(){
    printf("size compare\n");
    if (stat1.st_size > stat2.st_size) {
        printf("text 1 is bigger\n\n");
    }
    else if (stat1.st_size < stat2.st_size) {
        printf("text 2 is bigger\n\n");
    }
    else {
        printf("sizes are equal\n\n");
    }
}

**Comment by DohyoungSeong** [comment]
확인 했습니다
