### ISSUE TITLE
datecmp 코드 리뷰

### ISSUE THREAD

**Issue by kchs0529** [DohyoungSeong/Project2#12]
void sizecmp(){
    printf("size compare\n");
    if (stat1.st_size > stat2.st_size) {
        printf("text 1 is bigger\n\n");
    }
    else if (stat1.st_size < stat2.st_size) {
        printf("text 2 is bigger\n\n");
    }
    else {
        printf("sizes are equal\n\n");
    }
}
1.stat1 size와 stat2 size를 비교하여 stat 1이 더 큰 경우
2.stat1 size와 stat2 size를 비교하여 stat 2이 더 큰 경우
3.size 가 같은 경우

**Comment by DohyoungSeong** [comment]
확인 했습니다
