### ISSUE TITLE
timecmp 기반 기술 조사

### ISSUE THREAD

**Issue by DohyoungSeong** [DohyoungSeong/Project2#15]

**Comment by kchs0529** [comment]
확인했습니다

**Comment by DohyoungSeong** [comment]
C 언어의 time.h 헤더 파일에서 제공하는 localtime 함수를 사용하여 파일의 수정 시간 정보를 가져온다. 그 정보는 tm 구조체의 시, 분, 초 에 각각 저장되고, 비교후 결과가 출력된다.
