### ISSUE TITLE
filetime() 기반 기술 조사

### ISSUE THREAD

**Issue by DohyoungSeong** [DohyoungSeong/Project2#25]

**Comment by DohyoungSeong** [comment]
C 언어의 sys/stat.h와 time.h 헤더 파일을 사용하여 최근 수정 시간 정보를 불러온다. stat 구조체의 st_mtime 멤버에 최근 수정 시간이 저장되어 있다. 이 값을 localtime 함수를 사용하여 tm 구조체로 변환하여 비교한다.

**Comment by kchs0529** [comment]
확인했습니다
