### ISSUE TITLE
datecmp 기반 기술 조사

### ISSUE THREAD

**Issue by DohyoungSeong** [DohyoungSeong/Project2#27]

**Comment by kchs0529** [comment]
확인했습니다

**Comment by kchs0529** [comment]
localtime()함수는 time_t값을 활용할 수 있게 가공 시켜주는 함수로
#include <time.h>
struct tm * localtime(const time_t* timep);로 사용이 가능하다
datecmp함수는 if else if문을 이용하여 각각의 시간을 비교하여 더 빨리 수정된 파일을 찾아낸다

**Comment by DohyoungSeong** [comment]
확인 했습니다
