### ISSUE TITLE
filetime() 코드 리뷰

### ISSUE THREAD

**Issue by kchs0529** [DohyoungSeong/Project2#31]
void filetime1(){
    time1 = localtime(&stat1.st_mtime);
}

//파일 2의 시간 정보를 가져오는 함수 작성
void filetime2(){
    time2 = localtime(&stat2.st_mtime);
}
time1과 time2를 localtime을 이용하여 각각 저장한다

**Comment by DohyoungSeong** [comment]
확인 했습니다

**Comment by DohyoungSeong** [comment]
1. stat 구조체의 st_mtime 멤버를 사용하여 최근 수정 시간을 로드
2. localtime 함수를 사용하여 최근 수정 시간을 tm 구조체로 변환

**Comment by DohyoungSeong** [comment]
확인 했습니다
