### ISSUE TITLE
filestat 코드 리뷰

### ISSUE THREAD

**Issue by kchs0529** [DohyoungSeong/Project2#4]
void filestat1(){
    stat("text1", &stat1);
} 
파일 1의 정보를 받아오는 함수를 stat 함수를 이용하여 작성하였다

void filestat2(){
    stat("text2", &stat2);
}
파일 2의 정보를 받아오는 함수를 stat 함수를 이용하여 작성하였다

**Comment by DohyoungSeong** [comment]
확인 했습니다

**Comment by DohyoungSeong** [comment]
확인 했습니다
