### ISSUE TITLE
filestat 코드 작성

### ISSUE THREAD

**Issue by kchs0529** [DohyoungSeong/Project2#7]
//파일 1의 정보를 가져오는 함수 작성
void filestat1(){
    stat("text1", &stat1);
}

//파일 2의 정보를 가져오는 함수 작성
void filestat2(){
    stat("text2", &stat2);
}
파일 1과 2의 정보를 가져오는 함수입니다

**Comment by DohyoungSeong** [comment]
확인했습니다

**Comment by DohyoungSeong** [comment]
확인 했습니다.
