### ISSUE TITLE
sizecmp 코드 작성

### ISSUE THREAD

**Issue by kchs0529** [DohyoungSeong/Project2#8]
void sizecmp(){
    printf("size compare\n");
    if (stat1.st_size > stat2.st_size) {
        printf("text 1 is bigger\n\n");
    }
    else if (stat1.st_size < stat2.st_size) {
        printf("text 2 is bigger\n\n");
    }
    else {
        printf("sizes are equal\n\n");
    }
}
if문을 활용하여 각각의 파일의 크기를 비교한다

**Comment by DohyoungSeong** [comment]
확인 했습니다
